export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const NEW_PHOTO_USER =  "NEW_PHOTO_USER"
export const  NEW_PHOTO_PICKER = " NEW_PHOTO_PICKER"
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE"
